# Generated by Django 5.2.6 on 2025-09-09 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("results_file", models.CharField(max_length=200)),
                ("results_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
