# Generated by Django 5.2.6 on 2025-09-09 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
